services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LPC\LpcPetition\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Domain/Validator/*'

  LPC\LpcPetition\Controller\BackendController:
    public: true
